#TRANSFORM:
#  TEST_METHODS: ('Resize', 'CenterCrop', 'ToTensor', 'Normalize')
#  TEST_RESIZE: (224, )
#  TEST_CROP: (224, 224)
#  MEAN: (0.45, 0.45, 0.45)
#  STD: (0.225, 0.225, 0.225)
MODEL:
  CONV:
    TYPE: 'Conv2d'
  NORM:
    TYPE: 'BatchNorm2d'
    SYNC_BN: False
    FIX_BN: False
    PARTIAL_BN: False
  ACT:
    TYPE: 'ReLU'
  BACKBONE:
    NAME: 'ResNet'
    IN_PLANES: 3
    ARCH: 'resnet50'
    BASE_PLANES: 64
    LAYER_PLANES: (64, 128, 256, 512)
    DOWNSAMPLES: (0, 1, 1, 1)
  HEAD:
    NAME: 'GeneralHead2D'
    FEATURE_DIMS: 2048
    DROPOUT_RATE: 0.
    NUM_CLASSES: 10
  RECOGNIZER:
    NAME: 'ResNet'
    PRELOADED: ""
    PRETRAINED: ""
    PRETRAINED_NUM_CLASSES: 1000
    ZERO_INIT_RESIDUAL: True